sudo yo reveal
sudo yo reveal:slide "Space Apps"
sudo yo reveal:slide "About Me"
sudo yo reveal:slide "Hackathon"
sudo yo reveal:slide "Actividad Social"
sudo yo reveal:slide "Escuchar"
sudo yo reveal:slide "Trabajar Duro"
sudo yo reveal:slide "Recursos Limitados"
sudo yo reveal:slide "Ley del Menor Esfuerzo"
sudo yo reveal:slide "Tiempo Pomodoro"
sudo yo reveal:slide "Divertirse"
sudo yo reveal:slide "Nunca Rendirse"
sudo yo reveal:slide "Github"
sudo yo reveal:slide "Ser Ordenado"
sudo yo reveal:slide "Contencion"
sudo yo reveal:slide "Viajar"
sudo yo reveal:slide "Git Hub Github"
sudo yo reveal:slide "Aprender Interactivo"
sudo yo reveal:slide "Thanks"


